// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGouCEr8XD87QzCsy3aTsiCUpPqLWCHM',
    appId: '1:294409469331:web:b71348ce6d94bba785fc66',
    messagingSenderId: '294409469331',
    projectId: 'pracfirebase3-69728',
    authDomain: 'pracfirebase3-69728.firebaseapp.com',
    storageBucket: 'pracfirebase3-69728.appspot.com',
    measurementId: 'G-3R0169YVRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCX03Ni9WhCj449ZwKU1xPOxbKUafO95E',
    appId: '1:294409469331:android:03c166c8731a256085fc66',
    messagingSenderId: '294409469331',
    projectId: 'pracfirebase3-69728',
    storageBucket: 'pracfirebase3-69728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZiR6NzjqusP8Tne4Ck0qD0rbqmT1KEMQ',
    appId: '1:294409469331:ios:1e6807cce662796485fc66',
    messagingSenderId: '294409469331',
    projectId: 'pracfirebase3-69728',
    storageBucket: 'pracfirebase3-69728.appspot.com',
    iosBundleId: 'com.example.fluterapp5Apiprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZiR6NzjqusP8Tne4Ck0qD0rbqmT1KEMQ',
    appId: '1:294409469331:ios:94e046850bd3feb685fc66',
    messagingSenderId: '294409469331',
    projectId: 'pracfirebase3-69728',
    storageBucket: 'pracfirebase3-69728.appspot.com',
    iosBundleId: 'com.example.fluterapp5Apiprovider.RunnerTests',
  );
}
