// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVE9tsRFt-dkPv-SjXPJKVd51KjpjGAMc',
    appId: '1:615985904719:web:c0cf310735e6fe07e37e3a',
    messagingSenderId: '615985904719',
    projectId: 'ecomm-app-7e48c',
    authDomain: 'ecomm-app-7e48c.firebaseapp.com',
    storageBucket: 'ecomm-app-7e48c.appspot.com',
    measurementId: 'G-HN9DGEGJC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUhI59hsAQmBL1KwDzT2liy4rT1Xwifjs',
    appId: '1:615985904719:android:7ae1657c1810d55ee37e3a',
    messagingSenderId: '615985904719',
    projectId: 'ecomm-app-7e48c',
    storageBucket: 'ecomm-app-7e48c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjLh48S3I8-kFoVhMc2ntzJ1qFDe94Fpg',
    appId: '1:615985904719:ios:33bb8b92115101f3e37e3a',
    messagingSenderId: '615985904719',
    projectId: 'ecomm-app-7e48c',
    storageBucket: 'ecomm-app-7e48c.appspot.com',
    iosBundleId: 'com.example.flutterapp3MultiproviderFilterappEcommui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjLh48S3I8-kFoVhMc2ntzJ1qFDe94Fpg',
    appId: '1:615985904719:ios:0878632aa1a37fbae37e3a',
    messagingSenderId: '615985904719',
    projectId: 'ecomm-app-7e48c',
    storageBucket: 'ecomm-app-7e48c.appspot.com',
    iosBundleId: 'com.example.flutterapp3MultiproviderFilterappEcommui.RunnerTests',
  );
}
